export const url = 'https://api.nytimes.com/svc/topstories/v2/';
export const apiKey = '.json?api-key=0751ffff01d7a70710354972fa0ad4a9';
export const filters = [
    'arts',
    'automobiles',
    'books',
    'business',
    'fashion',
    'food',
    'health',
    'home',
    'insider',
    'magazine',
    'movies',
    'national',
    'nyregion',
    'obituaries',
    'opinion',
    'politics',
    'realestate',
    'science',
    'sports',
    'sundayreview',
    'technology',
    'theater',
    'tmagazine',
    'travel',
    'upshot',
    'world',
];
